### ISSUE TITLE
numeric power cleanup

### ISSUE THREAD

**Issue by rwst** [pynac/pynac#252]
- [x] make `numeric::power` return `ex`, see also #180
- [x] write our own `rational_power_parts()` #221
- [x] write our own `iquo`
- [x] check for denominator `1` in exponent #237
- [x] `MPZ`/`MPQ` `^` `MPQ` expression shortcut #251
- [x] in `rational_power_parts()` check if `factor_limit` can be reduced

Some data for the `factor_limit` issue:
```
sage: b=SR(4/11)
sage: a=SR(11)
sage: %timeit _=a^b
10000 loops, best of 3: 25.5 µs per loop
sage: a=SR(111111111111111)
sage: %timeit _=a^b
10000 loops, best of 3: 79.4 µs per loop
sage: a=SR(1111111111111111111111111)
sage: %timeit _=a^b
1000 loops, best of 3: 612 µs per loop
```
New timings are all < 30µs. Also for example:
```
sage: a=SR(101^41*3)
sage: %timeit _=(101^41*3)^(1/41)
10000 loops, best of 3: 82.7 µs per loop
sage: %timeit _=a^(1/41)
10000 loops, best of 3: 45.3 µs per loop
```
